service: serverless-embedings-generator

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements
  - serverless-lift
